// Created and developed by Jai Singh
// ---------------------------------------------------------------------------
// Object catalog — the parametric "furniture library" for the 3D editor.
// ---------------------------------------------------------------------------
// Each entry is a kind the user can drop into the scene: default dimensions
// (world units ~cm), a soft default colour, a library category, and a Lucide
// icon for the picker. The geometry recipe per kind lives in objects/SceneObject
// (a switch on `kind`). Adding a new object = one entry here + one case there.
import {
  Archive,
  Armchair,
  ArrowUpFromLine,
  BatteryCharging,
  Bot,
  Box,
  Boxes,
  BrickWall,
  Building2,
  CircleDot,
  Columns2,
  Columns3,
  Cone,
  Construction,
  Container,
  Cylinder,
  Disc3,
  DoorClosed,
  DoorOpen,
  Fan,
  Fence,
  FireExtinguisher,
  Flame,
  Forklift,
  Grid3x3,
  House,
  Layers2,
  Layers3,
  Lock,
  Luggage,
  Monitor,
  MoveHorizontal,
  MoveVertical,
  Package,
  Package2,
  Presentation,
  RectangleHorizontal,
  Rows3,
  Scale,
  ShowerHead,
  Signpost,
  Sofa,
  Sprout,
  Table,
  Tractor,
  Trash2,
  TreePine,
  Truck,
  TrendingUp,
  Users,
  Warehouse,
  type LucideIcon,
} from 'lucide-react'
import type { SceneObjectKind } from '../types'

export type ObjectCategory =
  | 'rooms'
  | 'furniture'
  | 'equipment'
  | 'vehicles'
  | 'structure'
  | 'storage'
  | 'decor'

export interface ObjectCatalogEntry {
  kind: SceneObjectKind
  label: string
  category: ObjectCategory
  icon: LucideIcon
  /** Default footprint + height in world units (~cm). */
  width: number
  depth: number
  height: number
  /** Soft default colour (overridable per-object). */
  color: string
  description: string
}

export const OBJECT_CATALOG: ObjectCatalogEntry[] = [
  // ── Rooms ────────────────────────────────────────────────────────────────
  {
    kind: 'office',
    label: 'Office',
    category: 'rooms',
    icon: Building2,
    width: 400,
    depth: 350,
    height: 270,
    color: '#e9edf4',
    description: 'Enclosed office with glass front',
  },
  {
    kind: 'meeting_room',
    label: 'Meeting Room',
    category: 'rooms',
    icon: Users,
    width: 520,
    depth: 420,
    height: 270,
    color: '#e6ecf5',
    description: 'Larger glass-walled meeting room',
  },
  // ── Furniture ──────────────────────────────────────────────────────────────
  {
    kind: 'desk',
    label: 'Desk',
    category: 'furniture',
    icon: Armchair,
    width: 160,
    depth: 75,
    height: 74,
    color: '#c79a6b',
    description: 'Office desk with monitor',
  },
  {
    kind: 'table',
    label: 'Table',
    category: 'furniture',
    icon: Table,
    width: 120,
    depth: 120,
    height: 74,
    color: '#caa377',
    description: 'Work / break table',
  },
  {
    kind: 'chair',
    label: 'Chair',
    category: 'furniture',
    icon: Armchair,
    width: 50,
    depth: 52,
    height: 90,
    color: '#64748b',
    description: 'Office / break-room chair',
  },
  {
    kind: 'sofa',
    label: 'Sofa',
    category: 'furniture',
    icon: Sofa,
    width: 190,
    depth: 85,
    height: 80,
    color: '#7186a3',
    description: 'Lounge / lobby sofa',
  },
  {
    kind: 'workstation',
    label: 'Workstation',
    category: 'furniture',
    icon: Monitor,
    width: 180,
    depth: 80,
    height: 115,
    color: '#9aa6b6',
    description: 'Packing / inspection station',
  },
  {
    kind: 'cabinet',
    label: 'Cabinet',
    category: 'furniture',
    icon: Archive,
    width: 90,
    depth: 45,
    height: 180,
    color: '#b8c0cc',
    description: 'Storage cabinet',
  },
  {
    kind: 'locker',
    label: 'Lockers',
    category: 'furniture',
    icon: Lock,
    width: 120,
    depth: 50,
    height: 190,
    color: '#8da0b8',
    description: 'Staff locker bank',
  },
  {
    kind: 'shelf_unit',
    label: 'Shelf Unit',
    category: 'furniture',
    icon: Rows3,
    width: 180,
    depth: 50,
    height: 200,
    color: '#9aa6b6',
    description: 'Open shelving unit',
  },
  {
    kind: 'counter',
    label: 'Counter',
    category: 'furniture',
    icon: RectangleHorizontal,
    width: 220,
    depth: 65,
    height: 95,
    color: '#e3e8f0',
    description: 'Service / break-room counter',
  },
  {
    kind: 'partition',
    label: 'Partition',
    category: 'furniture',
    icon: Columns2,
    width: 150,
    depth: 8,
    height: 160,
    color: '#aebacb',
    description: 'Cubicle divider screen',
  },
  {
    kind: 'whiteboard',
    label: 'Whiteboard',
    category: 'furniture',
    icon: Presentation,
    width: 180,
    depth: 50,
    height: 190,
    color: '#f5f8fc',
    description: 'Mobile whiteboard',
  },
  // ── Equipment ───────────────────────────────────────────────────────────────
  {
    kind: 'conveyor',
    label: 'Conveyor',
    category: 'equipment',
    icon: MoveHorizontal,
    width: 600,
    depth: 80,
    height: 90,
    color: '#8b97a8',
    description: 'Roller / belt conveyor line',
  },
  // ── Vehicles ────────────────────────────────────────────────────────────────
  // Brand-spec fleet — default footprints from the published real-world specs
  // (Raymond 7500 / 9800, Crown SP 3500 / RC 5500 / PE) in world cm.
  {
    kind: 'forklift',
    label: 'Counterbalance (sit-down)',
    category: 'vehicles',
    icon: Tractor,
    width: 250,
    depth: 120,
    height: 220,
    color: '#f59e0b',
    description: 'Sit-down counterbalance forklift',
  },
  {
    kind: 'forklift_reach',
    label: 'Reach Truck — Raymond',
    category: 'vehicles',
    icon: Forklift,
    width: 280,
    depth: 122,
    height: 240,
    color: '#c2342c',
    description:
      'Raymond 7500-class stand-up reach truck (48" chassis, straddle baselegs)',
  },
  {
    kind: 'forklift_orderpicker',
    label: 'Order Picker — Crown',
    category: 'vehicles',
    icon: ArrowUpFromLine,
    width: 310,
    depth: 107,
    height: 275,
    color: '#d6c9a3',
    description: 'Crown SP 3500-class man-up order picker (42" × 122")',
  },
  {
    kind: 'forklift_standup',
    label: 'Stand-Up — Crown',
    category: 'vehicles',
    icon: Forklift,
    width: 175,
    depth: 107,
    height: 224,
    color: '#d6c9a3',
    description: 'Crown RC 5500-class stand-up counterbalance (42" × 68")',
  },
  {
    kind: 'forklift_turret',
    label: 'Turret Truck — Raymond',
    category: 'vehicles',
    icon: MoveVertical,
    width: 350,
    depth: 152,
    height: 400,
    color: '#c2342c',
    description: 'Raymond 9800-class VNA swing-reach turret truck (60" wide)',
  },
  {
    kind: 'pallet_truck_rider',
    label: 'Rider Pallet Truck',
    category: 'vehicles',
    icon: Forklift,
    width: 200,
    depth: 91,
    height: 147,
    color: '#d6c9a3',
    description: 'Crown PE-class end-rider electric pallet truck',
  },
  {
    kind: 'walkie_stacker',
    label: 'Walkie Stacker',
    category: 'vehicles',
    icon: Forklift,
    width: 180,
    depth: 90,
    height: 190,
    color: '#d6c9a3',
    description: 'Pedestrian straddle stacker with tiller',
  },
  {
    kind: 'tugger',
    label: 'Tow Tugger',
    category: 'vehicles',
    icon: Tractor,
    width: 160,
    depth: 90,
    height: 125,
    color: '#c2342c',
    description: 'Seated tow tractor for cart trains',
  },
  {
    kind: 'pallet_jack',
    label: 'Pallet Jack',
    category: 'vehicles',
    icon: Forklift,
    width: 160,
    depth: 65,
    height: 120,
    color: '#ea580c',
    description: 'Manual pallet jack',
  },
  {
    kind: 'hand_truck',
    label: 'Hand Truck',
    category: 'vehicles',
    icon: Luggage,
    width: 55,
    depth: 55,
    height: 125,
    color: '#dc2626',
    description: 'Two-wheel dolly',
  },
  {
    kind: 'agv_robot',
    label: 'AGV Robot',
    category: 'vehicles',
    icon: Bot,
    width: 95,
    depth: 65,
    height: 35,
    color: '#334155',
    description: 'Autonomous floor robot',
  },
  {
    kind: 'scissor_lift',
    label: 'Scissor Lift',
    category: 'equipment',
    icon: ArrowUpFromLine,
    width: 180,
    depth: 100,
    height: 250,
    color: '#f59e0b',
    description: 'Scissor lift (stowed)',
  },
  {
    kind: 'ladder',
    label: 'Ladder',
    category: 'equipment',
    icon: MoveVertical,
    width: 60,
    depth: 120,
    height: 190,
    color: '#fbbf24',
    description: 'Rolling / step ladder',
  },
  {
    kind: 'floor_scale',
    label: 'Floor Scale',
    category: 'equipment',
    icon: Scale,
    width: 130,
    depth: 130,
    height: 110,
    color: '#94a3b8',
    description: 'Pallet weighing scale',
  },
  {
    kind: 'stretch_wrapper',
    label: 'Wrapper',
    category: 'equipment',
    icon: Disc3,
    width: 190,
    depth: 190,
    height: 240,
    color: '#64748b',
    description: 'Stretch-wrap turntable',
  },
  {
    kind: 'charging_station',
    label: 'Charging',
    category: 'equipment',
    icon: BatteryCharging,
    width: 80,
    depth: 60,
    height: 150,
    color: '#34d399',
    description: 'Equipment charging station',
  },
  {
    kind: 'trash_bin',
    label: 'Trash Bin',
    category: 'equipment',
    icon: Trash2,
    width: 55,
    depth: 55,
    height: 95,
    color: '#52606f',
    description: 'Waste / recycling bin',
  },
  {
    kind: 'fan',
    label: 'Floor Fan',
    category: 'equipment',
    icon: Fan,
    width: 65,
    depth: 65,
    height: 185,
    color: '#8b97a8',
    description: 'Industrial pedestal fan',
  },
  {
    kind: 'fire_extinguisher',
    label: 'Extinguisher',
    category: 'equipment',
    icon: FireExtinguisher,
    width: 22,
    depth: 22,
    height: 60,
    color: '#dc2626',
    description: 'Fire extinguisher',
  },
  {
    kind: 'floor_scrubber',
    label: 'Floor Scrubber',
    category: 'equipment',
    icon: Disc3,
    width: 150,
    depth: 90,
    height: 140,
    color: '#0e7490',
    description: 'Ride-on floor scrubber',
  },
  {
    kind: 'baler',
    label: 'Baler',
    category: 'equipment',
    icon: Archive,
    width: 180,
    depth: 120,
    height: 280,
    color: '#475569',
    description: 'Vertical cardboard baler',
  },
  {
    kind: 'air_compressor',
    label: 'Compressor',
    category: 'equipment',
    icon: Cylinder,
    width: 130,
    depth: 70,
    height: 125,
    color: '#64748b',
    description: 'Shop air compressor',
  },
  {
    kind: 'battery_rack',
    label: 'Battery Rack',
    category: 'equipment',
    icon: BatteryCharging,
    width: 240,
    depth: 80,
    height: 180,
    color: '#334155',
    description: 'Forklift battery charging rack',
  },
  {
    kind: 'eyewash_station',
    label: 'Eyewash',
    category: 'equipment',
    icon: ShowerHead,
    width: 60,
    depth: 60,
    height: 135,
    color: '#10b981',
    description: 'Safety eyewash station',
  },
  // ── Structure ───────────────────────────────────────────────────────────────
  {
    kind: 'column',
    label: 'Column',
    category: 'structure',
    icon: Columns3,
    width: 45,
    depth: 45,
    height: 500,
    color: '#cdd4de',
    description: 'Structural support column',
  },
  {
    kind: 'dock_door',
    label: 'Dock Door',
    category: 'structure',
    icon: Warehouse,
    width: 300,
    depth: 30,
    height: 360,
    color: '#aeb8c6',
    description: 'Loading dock roller door',
  },
  {
    kind: 'door',
    label: 'Door',
    category: 'structure',
    icon: DoorOpen,
    width: 100,
    depth: 18,
    height: 210,
    color: '#9aa6b6',
    description: 'Interior doorway',
  },
  {
    kind: 'barrier',
    label: 'Barrier',
    category: 'structure',
    icon: Construction,
    width: 200,
    depth: 12,
    height: 110,
    color: '#fbbf24',
    description: 'Safety barrier',
  },
  {
    kind: 'safety_rail',
    label: 'Safety Rail',
    category: 'structure',
    icon: Fence,
    width: 300,
    depth: 8,
    height: 120,
    color: '#fde047',
    description: 'Pedestrian guard rail',
  },
  {
    kind: 'sign',
    label: 'Sign',
    category: 'structure',
    icon: Signpost,
    width: 60,
    depth: 10,
    height: 210,
    color: '#60a5fa',
    description: 'Wayfinding / zone sign',
  },
  // Building blocks — sized in whole grid-friendly units so they paint, stack
  // and adjoin cleanly in build mode.
  {
    kind: 'wall',
    label: 'Wall',
    category: 'structure',
    icon: BrickWall,
    width: 200,
    depth: 20,
    height: 300,
    color: '#dde3ec',
    description: 'Wall segment — paint runs, stack for height',
  },
  {
    kind: 'platform',
    label: 'Platform',
    category: 'structure',
    icon: Layers2,
    width: 200,
    depth: 200,
    height: 20,
    color: '#c3ccda',
    description: 'Raised deck tile — stack into mezzanines',
  },
  {
    kind: 'stairs',
    label: 'Stairs',
    category: 'structure',
    icon: TrendingUp,
    width: 120,
    depth: 240,
    height: 150,
    color: '#aeb8c6',
    description: 'Step run between levels',
  },
  {
    kind: 'ramp',
    label: 'Ramp',
    category: 'structure',
    icon: TrendingUp,
    width: 160,
    depth: 320,
    height: 100,
    color: '#b6bfce',
    description: 'Sloped access ramp',
  },
  {
    kind: 'fence',
    label: 'Fence',
    category: 'structure',
    icon: Grid3x3,
    width: 200,
    depth: 10,
    height: 180,
    color: '#9aa6b6',
    description: 'Wire fence segment — paint runs',
  },
  {
    kind: 'gate',
    label: 'Gate',
    category: 'structure',
    icon: DoorClosed,
    width: 300,
    depth: 15,
    height: 180,
    color: '#8da0b8',
    description: 'Sliding yard gate',
  },
  {
    kind: 'bollard',
    label: 'Bollard',
    category: 'structure',
    icon: CircleDot,
    width: 20,
    depth: 20,
    height: 90,
    color: '#fbbf24',
    description: 'Impact protection post',
  },
  {
    kind: 'guard_shack',
    label: 'Guard Shack',
    category: 'structure',
    icon: House,
    width: 250,
    depth: 250,
    height: 280,
    color: '#e3e8f0',
    description: 'Security booth',
  },
  {
    kind: 'cone',
    label: 'Cone',
    category: 'structure',
    icon: Cone,
    width: 30,
    depth: 30,
    height: 50,
    color: '#f97316',
    description: 'Safety cone',
  },
  {
    kind: 'dock_leveler',
    label: 'Dock Leveler',
    category: 'structure',
    icon: Layers2,
    width: 200,
    depth: 250,
    height: 18,
    color: '#6b7280',
    description: 'Recessed dock leveler plate',
  },
  {
    kind: 'mirror_dome',
    label: 'Safety Mirror',
    category: 'structure',
    icon: CircleDot,
    width: 60,
    depth: 35,
    height: 250,
    color: '#f59e0b',
    description: 'Convex intersection mirror on pole',
  },
  {
    kind: 'semi_trailer',
    label: 'Semi Trailer',
    category: 'structure',
    icon: Truck,
    width: 1615,
    depth: 260,
    height: 400,
    color: '#e2e8f0',
    description: '53-ft dry van trailer (docked)',
  },
  // ── Storage ─────────────────────────────────────────────────────────────────
  {
    kind: 'pallet',
    label: 'Pallet',
    category: 'storage',
    icon: Package,
    width: 120,
    depth: 100,
    height: 16,
    color: '#b98a52',
    description: 'Empty pallet',
  },
  {
    kind: 'pallet_stack',
    label: 'Pallet + Load',
    category: 'storage',
    icon: Boxes,
    width: 120,
    depth: 100,
    height: 160,
    color: '#c79a6b',
    description: 'Loaded pallet stack',
  },
  {
    kind: 'drum',
    label: 'Drum',
    category: 'storage',
    icon: Cylinder,
    width: 60,
    depth: 60,
    height: 90,
    color: '#2563eb',
    description: '55-gal steel drum',
  },
  {
    kind: 'crate_stack',
    label: 'Crates',
    category: 'storage',
    icon: Box,
    width: 110,
    depth: 110,
    height: 130,
    color: '#c79a6b',
    description: 'Stacked wooden crates',
  },
  {
    kind: 'gaylord',
    label: 'Gaylord',
    category: 'storage',
    icon: Package2,
    width: 120,
    depth: 100,
    height: 120,
    color: '#cfa46f',
    description: 'Bulk gaylord box on pallet',
  },
  {
    kind: 'tote_stack',
    label: 'Totes',
    category: 'storage',
    icon: Layers3,
    width: 60,
    depth: 40,
    height: 95,
    color: '#3b82f6',
    description: 'Stacked plastic totes',
  },
  {
    kind: 'shipping_container',
    label: 'Container',
    category: 'storage',
    icon: Container,
    width: 606,
    depth: 244,
    height: 259,
    color: '#1e6091',
    description: '20-ft shipping container',
  },
  {
    kind: 'ibc_tote',
    label: 'IBC Tote',
    category: 'storage',
    icon: Box,
    width: 120,
    depth: 100,
    height: 116,
    color: '#e5e7eb',
    description: 'IBC liquid tote in steel cage',
  },
  {
    kind: 'propane_cage',
    label: 'Propane Cage',
    category: 'storage',
    icon: Flame,
    width: 150,
    depth: 80,
    height: 180,
    color: '#fbbf24',
    description: 'LP tank exchange cage',
  },
  {
    kind: 'dumpster',
    label: 'Dumpster',
    category: 'storage',
    icon: Trash2,
    width: 240,
    depth: 140,
    height: 135,
    color: '#3f6212',
    description: 'Front-load waste dumpster',
  },
  // ── Decor ───────────────────────────────────────────────────────────────────
  {
    kind: 'plant',
    label: 'Plant',
    category: 'decor',
    icon: Sprout,
    width: 60,
    depth: 60,
    height: 140,
    color: '#6aa84f',
    description: 'Potted plant',
  },
  {
    kind: 'tree',
    label: 'Tree',
    category: 'decor',
    icon: TreePine,
    width: 130,
    depth: 130,
    height: 360,
    color: '#4c8a4a',
    description: 'Outdoor evergreen tree',
  },
]

export const CATALOG_BY_KIND: Record<string, ObjectCatalogEntry> =
  Object.fromEntries(OBJECT_CATALOG.map((e) => [e.kind, e]))

export const CATEGORY_ORDER: ObjectCategory[] = [
  'rooms',
  'furniture',
  'equipment',
  'vehicles',
  'storage',
  'structure',
  'decor',
]

export const CATEGORY_LABEL: Record<ObjectCategory, string> = {
  rooms: 'Rooms & Offices',
  furniture: 'Furniture',
  equipment: 'Equipment',
  vehicles: 'Vehicles & Fleet',
  storage: 'Storage',
  structure: 'Structure',
  decor: 'Decor',
}

// Created and developed by Jai Singh
