# Created and developed by Jai Singh
"""Wizard output → config.load round-trip."""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from omni_agent.master.config import load_config, master_config_path  # noqa: E402
from omni_agent.master.pair_sessions_logic import default_worker_pairings  # noqa: E402
from omni_agent.master.wizard import build_config_from_state, persist_wizard  # noqa: E402
from omni_agent.master.wizard_state import WizardState, clear_wizard_state  # noqa: E402


@pytest.fixture
def isolated_home(monkeypatch: pytest.MonkeyPatch, tmp_path: Path):
    home = tmp_path / ".omniframe"
    home.mkdir()
    monkeypatch.setenv("USERPROFILE", str(tmp_path))
    import omni_agent.master.config as cfg_mod
    import omni_agent.master.wizard_state as ws_mod

    monkeypatch.setattr(cfg_mod, "omniframe_home", lambda: home)
    monkeypatch.setattr(ws_mod, "omniframe_home", lambda: home)
    monkeypatch.setattr(cfg_mod, "master_config_path", lambda: home / "master_config.yaml")
    monkeypatch.setattr(ws_mod, "wizard_state_path", lambda: home / "wizard_state.json")
    yield home


def test_write_master_config_roundtrip(isolated_home: Path):
    pairings = [p.to_dict() for p in default_worker_pairings(2, host_prefix="QA")]
    state = WizardState(
        worker_count=2,
        host_prefix="QA",
        pairings=pairings,
        saplogon_path="C:\\SAP\\saplogon.exe",
    )
    cfg = persist_wizard(state)
    assert cfg.master.workers == 2
    assert len(cfg.workers) == 2
    assert cfg.workers[0].id == "QA-W1"
    assert cfg.using_builtin_defaults is False
    path = master_config_path()
    assert path.is_file()
    assert "Generated by Setup Wizard" in path.read_text(encoding="utf-8")
    reloaded = load_config(path)
    assert reloaded.workers[1].health_port == 8766
    clear_wizard_state()
    assert not (isolated_home / "wizard_state.json").exists()


def test_build_config_validates_duplicates(isolated_home: Path):
    pairings = [p.to_dict() for p in default_worker_pairings(2, host_prefix="X")]
    pairings[1]["sess_idx"] = pairings[0]["sess_idx"]
    state = WizardState(worker_count=2, host_prefix="X", pairings=pairings)
    with pytest.raises(ValueError, match="Duplicate"):
        build_config_from_state(state)

# Created and developed by Jai Singh
