#!/usr/bin/env node
/**
 * Lint Ratchet — prevents lint quality from regressing.
 *
 * Usage:
 *   node scripts/lint-ratchet.mjs           # Check against baseline (CI mode)
 *   node scripts/lint-ratchet.mjs --update  # Recalculate and save a new baseline
 *
 * The baseline is stored in .lint-baseline.json at the repo root.
 * Warning count and suppression count must not exceed the baseline values.
 */

import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { resolve, dirname, extname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const BASELINE_PATH = resolve(ROOT, '.lint-baseline.json')
const UPDATE_FLAG = process.argv.includes('--update')

// ── helpers ──────────────────────────────────────────────────────────────

function countWarnings() {
  try {
    const raw = execSync('pnpm eslint --format json .', {
      cwd: ROOT,
      encoding: 'utf-8',
      maxBuffer: 50 * 1024 * 1024, // 50 MB — large codebases can produce a lot of JSON
      stdio: ['pipe', 'pipe', 'pipe'],
    })

    const files = JSON.parse(raw)
    let warnings = 0
    let errors = 0

    for (const file of files) {
      warnings += file.warningCount ?? 0
      errors += file.errorCount ?? 0
    }

    return { warnings, errors }
  } catch (err) {
    // ESLint exits non-zero when there are errors; the JSON is on stdout
    if (err.stdout) {
      try {
        const files = JSON.parse(err.stdout)
        let warnings = 0
        let errors = 0
        for (const file of files) {
          warnings += file.warningCount ?? 0
          errors += file.errorCount ?? 0
        }
        return { warnings, errors }
      } catch {
        // Fall through
      }
    }
    console.error('Failed to run eslint:', err.message)
    process.exit(2)
  }
}

function walkDir(dir, exts) {
  const results = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      if (entry.name === 'node_modules' || entry.name === 'dist') continue
      results.push(...walkDir(full, exts))
    } else if (exts.includes(extname(entry.name))) {
      results.push(full)
    }
  }
  return results
}

function countSuppressions() {
  const srcDir = resolve(ROOT, 'src')
  const files = walkDir(srcDir, ['.ts', '.tsx'])
  const pattern = /eslint-disable/g
  let total = 0

  for (const file of files) {
    const content = readFileSync(file, 'utf-8')
    const matches = content.match(pattern)
    if (matches) total += matches.length
  }
  return total
}

function readBaseline() {
  try {
    return JSON.parse(readFileSync(BASELINE_PATH, 'utf-8'))
  } catch {
    return null
  }
}

function writeBaseline(data) {
  writeFileSync(BASELINE_PATH, JSON.stringify(data, null, 2) + '\n', 'utf-8')
}

// ── main ─────────────────────────────────────────────────────────────────

console.log('Lint Ratchet — checking code quality...\n')

const { warnings, errors } = countWarnings()
const suppressions = countSuppressions()

console.log(`  Warnings:     ${warnings}`)
console.log(`  Errors:       ${errors}`)
console.log(`  Suppressions: ${suppressions >= 0 ? suppressions : 'N/A'}`)
console.log()

if (UPDATE_FLAG) {
  const baseline = {
    maxWarnings: warnings,
    maxSuppressions: suppressions >= 0 ? suppressions : undefined,
    updatedAt: new Date().toISOString(),
    note: 'Auto-generated by scripts/lint-ratchet.mjs --update',
  }
  writeBaseline(baseline)
  console.log(`Baseline updated → ${BASELINE_PATH}`)
  console.log(JSON.stringify(baseline, null, 2))
  process.exit(0)
}

// ── compare against baseline ─────────────────────────────────────────────

const baseline = readBaseline()

if (!baseline) {
  console.error(
    'No .lint-baseline.json found. Run with --update to create one.'
  )
  process.exit(1)
}

console.log(`  Baseline max warnings:     ${baseline.maxWarnings}`)
if (baseline.maxSuppressions !== undefined) {
  console.log(`  Baseline max suppressions: ${baseline.maxSuppressions}`)
}
console.log()

let failed = false

if (warnings > baseline.maxWarnings) {
  console.error(
    `FAIL: Warning count (${warnings}) exceeds baseline (${baseline.maxWarnings}).`
  )
  console.error(
    `  Fix the new warnings or run 'node scripts/lint-ratchet.mjs --update' to raise the baseline.`
  )
  failed = true
} else if (warnings < baseline.maxWarnings) {
  console.log(
    `Nice! Warning count dropped from ${baseline.maxWarnings} → ${warnings}. Consider running --update to ratchet down.`
  )
}

if (
  baseline.maxSuppressions !== undefined &&
  suppressions >= 0 &&
  suppressions > baseline.maxSuppressions
) {
  console.error(
    `FAIL: Suppression count (${suppressions}) exceeds baseline (${baseline.maxSuppressions}).`
  )
  console.error(
    `  Remove unnecessary eslint-disable directives or run --update to raise the baseline.`
  )
  failed = true
} else if (
  baseline.maxSuppressions !== undefined &&
  suppressions >= 0 &&
  suppressions < baseline.maxSuppressions
) {
  console.log(
    `Nice! Suppression count dropped from ${baseline.maxSuppressions} → ${suppressions}. Consider running --update.`
  )
}

if (errors > 0) {
  console.error(`FAIL: ${errors} lint error(s) found. Errors must be zero.`)
  failed = true
}

if (failed) {
  process.exit(1)
}

console.log('PASS: Lint quality is within baseline.')
process.exit(0)
