/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupplyChainHarnessRouteImport } from './routes/supply-chain-harness'
import { Route as Scene3dHarnessRouteImport } from './routes/scene3d-harness'
import { Route as RfInterfaceRouteImport } from './routes/rf-interface'
import { Route as PrototypeRouteImport } from './routes/prototype'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as TimeclockappIndexRouteImport } from './routes/timeclockapp/index'
import { Route as RfInterfaceIndexRouteImport } from './routes/rf-interface/index'
import { Route as CustomerPortalIndexRouteImport } from './routes/customer-portal/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as CustomerPortalTicketIdRouteImport } from './routes/customer-portal/$ticketId'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authRfSigninRouteImport } from './routes/(auth)/rf-signin'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedSettingsOrganizationRouteImport } from './routes/_authenticated/settings/organization'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsCacheRouteImport } from './routes/_authenticated/settings/cache'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedIntelligenceDroneControlRouteImport } from './routes/_authenticated/intelligence/drone-control'
import { Route as AuthenticatedIntelligenceAiChatRouteImport } from './routes/_authenticated/intelligence/ai-chat'
import { Route as AuthenticatedHrTimeTrackerRouteImport } from './routes/_authenticated/hr/time-tracker'
import { Route as AuthenticatedHrEmployeeReviewsRouteImport } from './routes/_authenticated/hr/employee-reviews'
import { Route as AuthenticatedFacilityVendorManagementRouteImport } from './routes/_authenticated/facility/vendor-management'
import { Route as AuthenticatedFacilitySecurityRouteImport } from './routes/_authenticated/facility/security'
import { Route as AuthenticatedFacilityMaintenanceRouteImport } from './routes/_authenticated/facility/maintenance'
import { Route as AuthenticatedFacilityItServicesRouteImport } from './routes/_authenticated/facility/it-services'
import { Route as AuthenticatedBusinessWarehouseRouteImport } from './routes/_authenticated/business/warehouse'
import { Route as AuthenticatedBusinessTransportationRouteImport } from './routes/_authenticated/business/transportation'
import { Route as AuthenticatedBusinessSupplyChainRouteImport } from './routes/_authenticated/business/supply-chain'
import { Route as AuthenticatedBusinessLogisticsRouteImport } from './routes/_authenticated/business/logistics'
import { Route as AuthenticatedBusinessInventoryRouteImport } from './routes/_authenticated/business/inventory'
import { Route as AuthenticatedBusinessEngineeringRouteImport } from './routes/_authenticated/business/engineering'
import { Route as AuthenticatedBusinessCustomerServiceRouteImport } from './routes/_authenticated/business/customer-service'
import { Route as AuthenticatedAppsUnitPackRouteImport } from './routes/_authenticated/apps/unit-pack'
import { Route as AuthenticatedAppsTkaDataManagerRouteImport } from './routes/_authenticated/apps/tka-data-manager'
import { Route as AuthenticatedAppsStandardWorkRouteImport } from './routes/_authenticated/apps/standard-work'
import { Route as AuthenticatedAppsSmartsheetIntegrationsRouteImport } from './routes/_authenticated/apps/smartsheet-integrations'
import { Route as AuthenticatedAppsShiftProductivityRouteImport } from './routes/_authenticated/apps/shift-productivity'
import { Route as AuthenticatedAppsQualityRouteImport } from './routes/_authenticated/apps/quality'
import { Route as AuthenticatedAppsProductionBoardsRouteImport } from './routes/_authenticated/apps/production-boards'
import { Route as AuthenticatedAppsOutboundRouteImport } from './routes/_authenticated/apps/outbound'
import { Route as AuthenticatedAppsMyProductivityRouteImport } from './routes/_authenticated/apps/my-productivity'
import { Route as AuthenticatedAppsKittingRouteImport } from './routes/_authenticated/apps/kitting'
import { Route as AuthenticatedAppsInventoryRouteImport } from './routes/_authenticated/apps/inventory'
import { Route as AuthenticatedAppsInboundRouteImport } from './routes/_authenticated/apps/inbound'
import { Route as AuthenticatedAppsGrsRouteImport } from './routes/_authenticated/apps/grs'
import { Route as AuthenticatedAppsDataManagerRouteImport } from './routes/_authenticated/apps/data-manager'
import { Route as AuthenticatedAppsCustomerPortalRouteImport } from './routes/_authenticated/apps/customer-portal'
import { Route as AuthenticatedAdminTabPermissionsDebugRouteImport } from './routes/_authenticated/admin/tab-permissions-debug'
import { Route as AuthenticatedAdminSystemSettingsRouteImport } from './routes/_authenticated/admin/system-settings'
import { Route as AuthenticatedAdminSupplyChainMappingRouteImport } from './routes/_authenticated/admin/supply-chain-mapping'
import { Route as AuthenticatedAdminSessionManagementRouteImport } from './routes/_authenticated/admin/session-management'
import { Route as AuthenticatedAdminSapTestingRouteImport } from './routes/_authenticated/admin/sap-testing'
import { Route as AuthenticatedAdminPerformanceMonitorRouteImport } from './routes/_authenticated/admin/performance-monitor'
import { Route as AuthenticatedAdminDeviceManagerRouteImport } from './routes/_authenticated/admin/device-manager'
import { Route as AuthenticatedAdminWorkQueueIndexRouteImport } from './routes/_authenticated/admin/work-queue/index'
import { Route as AuthenticatedAdminWorkEngineIndexRouteImport } from './routes/_authenticated/admin/work-engine/index'
import { Route as AuthenticatedAdminUserManagementIndexRouteImport } from './routes/_authenticated/admin/user-management/index'
import { Route as AuthenticatedAdminRolesIndexRouteImport } from './routes/_authenticated/admin/roles/index'
import { Route as AuthenticatedAdminPermissionsIndexRouteImport } from './routes/_authenticated/admin/permissions/index'
import { Route as AuthenticatedAdminOnboardingIndexRouteImport } from './routes/_authenticated/admin/onboarding/index'
import { Route as AuthenticatedAdminOmnibeltIndexRouteImport } from './routes/_authenticated/admin/omnibelt/index'

const SupplyChainHarnessRoute = SupplyChainHarnessRouteImport.update({
  id: '/supply-chain-harness',
  path: '/supply-chain-harness',
  getParentRoute: () => rootRouteImport,
} as any)
const Scene3dHarnessRoute = Scene3dHarnessRouteImport.update({
  id: '/scene3d-harness',
  path: '/scene3d-harness',
  getParentRoute: () => rootRouteImport,
} as any)
const RfInterfaceRoute = RfInterfaceRouteImport.update({
  id: '/rf-interface',
  path: '/rf-interface',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeRoute = PrototypeRouteImport.update({
  id: '/prototype',
  path: '/prototype',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeclockappIndexRoute = TimeclockappIndexRouteImport.update({
  id: '/timeclockapp/',
  path: '/timeclockapp/',
  getParentRoute: () => rootRouteImport,
} as any)
const RfInterfaceIndexRoute = RfInterfaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RfInterfaceRoute,
} as any)
const CustomerPortalIndexRoute = CustomerPortalIndexRouteImport.update({
  id: '/customer-portal/',
  path: '/customer-portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CustomerPortalTicketIdRoute = CustomerPortalTicketIdRouteImport.update({
  id: '/customer-portal/$ticketId',
  path: '/customer-portal/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authRfSigninRoute = authRfSigninRouteImport.update({
  id: '/(auth)/rf-signin',
  path: '/rf-signin',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsOrganizationRoute =
  AuthenticatedSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsCacheRoute =
  AuthenticatedSettingsCacheRouteImport.update({
    id: '/cache',
    path: '/cache',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedIntelligenceDroneControlRoute =
  AuthenticatedIntelligenceDroneControlRouteImport.update({
    id: '/intelligence/drone-control',
    path: '/intelligence/drone-control',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntelligenceAiChatRoute =
  AuthenticatedIntelligenceAiChatRouteImport.update({
    id: '/intelligence/ai-chat',
    path: '/intelligence/ai-chat',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrTimeTrackerRoute =
  AuthenticatedHrTimeTrackerRouteImport.update({
    id: '/hr/time-tracker',
    path: '/hr/time-tracker',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrEmployeeReviewsRoute =
  AuthenticatedHrEmployeeReviewsRouteImport.update({
    id: '/hr/employee-reviews',
    path: '/hr/employee-reviews',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacilityVendorManagementRoute =
  AuthenticatedFacilityVendorManagementRouteImport.update({
    id: '/facility/vendor-management',
    path: '/facility/vendor-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacilitySecurityRoute =
  AuthenticatedFacilitySecurityRouteImport.update({
    id: '/facility/security',
    path: '/facility/security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacilityMaintenanceRoute =
  AuthenticatedFacilityMaintenanceRouteImport.update({
    id: '/facility/maintenance',
    path: '/facility/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacilityItServicesRoute =
  AuthenticatedFacilityItServicesRouteImport.update({
    id: '/facility/it-services',
    path: '/facility/it-services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessWarehouseRoute =
  AuthenticatedBusinessWarehouseRouteImport.update({
    id: '/business/warehouse',
    path: '/business/warehouse',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessTransportationRoute =
  AuthenticatedBusinessTransportationRouteImport.update({
    id: '/business/transportation',
    path: '/business/transportation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessSupplyChainRoute =
  AuthenticatedBusinessSupplyChainRouteImport.update({
    id: '/business/supply-chain',
    path: '/business/supply-chain',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessLogisticsRoute =
  AuthenticatedBusinessLogisticsRouteImport.update({
    id: '/business/logistics',
    path: '/business/logistics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessInventoryRoute =
  AuthenticatedBusinessInventoryRouteImport.update({
    id: '/business/inventory',
    path: '/business/inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessEngineeringRoute =
  AuthenticatedBusinessEngineeringRouteImport.update({
    id: '/business/engineering',
    path: '/business/engineering',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessCustomerServiceRoute =
  AuthenticatedBusinessCustomerServiceRouteImport.update({
    id: '/business/customer-service',
    path: '/business/customer-service',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsUnitPackRoute =
  AuthenticatedAppsUnitPackRouteImport.update({
    id: '/apps/unit-pack',
    path: '/apps/unit-pack',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsTkaDataManagerRoute =
  AuthenticatedAppsTkaDataManagerRouteImport.update({
    id: '/apps/tka-data-manager',
    path: '/apps/tka-data-manager',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsStandardWorkRoute =
  AuthenticatedAppsStandardWorkRouteImport.update({
    id: '/apps/standard-work',
    path: '/apps/standard-work',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsSmartsheetIntegrationsRoute =
  AuthenticatedAppsSmartsheetIntegrationsRouteImport.update({
    id: '/apps/smartsheet-integrations',
    path: '/apps/smartsheet-integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsShiftProductivityRoute =
  AuthenticatedAppsShiftProductivityRouteImport.update({
    id: '/apps/shift-productivity',
    path: '/apps/shift-productivity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsQualityRoute =
  AuthenticatedAppsQualityRouteImport.update({
    id: '/apps/quality',
    path: '/apps/quality',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsProductionBoardsRoute =
  AuthenticatedAppsProductionBoardsRouteImport.update({
    id: '/apps/production-boards',
    path: '/apps/production-boards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsOutboundRoute =
  AuthenticatedAppsOutboundRouteImport.update({
    id: '/apps/outbound',
    path: '/apps/outbound',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsMyProductivityRoute =
  AuthenticatedAppsMyProductivityRouteImport.update({
    id: '/apps/my-productivity',
    path: '/apps/my-productivity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsKittingRoute =
  AuthenticatedAppsKittingRouteImport.update({
    id: '/apps/kitting',
    path: '/apps/kitting',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsInventoryRoute =
  AuthenticatedAppsInventoryRouteImport.update({
    id: '/apps/inventory',
    path: '/apps/inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsInboundRoute =
  AuthenticatedAppsInboundRouteImport.update({
    id: '/apps/inbound',
    path: '/apps/inbound',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsGrsRoute = AuthenticatedAppsGrsRouteImport.update({
  id: '/apps/grs',
  path: '/apps/grs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsDataManagerRoute =
  AuthenticatedAppsDataManagerRouteImport.update({
    id: '/apps/data-manager',
    path: '/apps/data-manager',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsCustomerPortalRoute =
  AuthenticatedAppsCustomerPortalRouteImport.update({
    id: '/apps/customer-portal',
    path: '/apps/customer-portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTabPermissionsDebugRoute =
  AuthenticatedAdminTabPermissionsDebugRouteImport.update({
    id: '/tab-permissions-debug',
    path: '/tab-permissions-debug',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSystemSettingsRoute =
  AuthenticatedAdminSystemSettingsRouteImport.update({
    id: '/system-settings',
    path: '/system-settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSupplyChainMappingRoute =
  AuthenticatedAdminSupplyChainMappingRouteImport.update({
    id: '/supply-chain-mapping',
    path: '/supply-chain-mapping',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSessionManagementRoute =
  AuthenticatedAdminSessionManagementRouteImport.update({
    id: '/session-management',
    path: '/session-management',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSapTestingRoute =
  AuthenticatedAdminSapTestingRouteImport.update({
    id: '/sap-testing',
    path: '/sap-testing',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPerformanceMonitorRoute =
  AuthenticatedAdminPerformanceMonitorRouteImport.update({
    id: '/performance-monitor',
    path: '/performance-monitor',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDeviceManagerRoute =
  AuthenticatedAdminDeviceManagerRouteImport.update({
    id: '/device-manager',
    path: '/device-manager',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminWorkQueueIndexRoute =
  AuthenticatedAdminWorkQueueIndexRouteImport.update({
    id: '/work-queue/',
    path: '/work-queue/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminWorkEngineIndexRoute =
  AuthenticatedAdminWorkEngineIndexRouteImport.update({
    id: '/work-engine/',
    path: '/work-engine/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUserManagementIndexRoute =
  AuthenticatedAdminUserManagementIndexRouteImport.update({
    id: '/user-management/',
    path: '/user-management/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRolesIndexRoute =
  AuthenticatedAdminRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPermissionsIndexRoute =
  AuthenticatedAdminPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOnboardingIndexRoute =
  AuthenticatedAdminOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOmnibeltIndexRoute =
  AuthenticatedAdminOmnibeltIndexRouteImport.update({
    id: '/omnibelt/',
    path: '/omnibelt/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/intro': typeof IntroRoute
  '/prototype': typeof PrototypeRoute
  '/rf-interface': typeof RfInterfaceRouteWithChildren
  '/scene3d-harness': typeof Scene3dHarnessRoute
  '/supply-chain-harness': typeof SupplyChainHarnessRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/rf-signin': typeof authRfSigninRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/customer-portal/$ticketId': typeof CustomerPortalTicketIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/customer-portal': typeof CustomerPortalIndexRoute
  '/rf-interface/': typeof RfInterfaceIndexRoute
  '/timeclockapp': typeof TimeclockappIndexRoute
  '/admin/device-manager': typeof AuthenticatedAdminDeviceManagerRoute
  '/admin/performance-monitor': typeof AuthenticatedAdminPerformanceMonitorRoute
  '/admin/sap-testing': typeof AuthenticatedAdminSapTestingRoute
  '/admin/session-management': typeof AuthenticatedAdminSessionManagementRoute
  '/admin/supply-chain-mapping': typeof AuthenticatedAdminSupplyChainMappingRoute
  '/admin/system-settings': typeof AuthenticatedAdminSystemSettingsRoute
  '/admin/tab-permissions-debug': typeof AuthenticatedAdminTabPermissionsDebugRoute
  '/apps/customer-portal': typeof AuthenticatedAppsCustomerPortalRoute
  '/apps/data-manager': typeof AuthenticatedAppsDataManagerRoute
  '/apps/grs': typeof AuthenticatedAppsGrsRoute
  '/apps/inbound': typeof AuthenticatedAppsInboundRoute
  '/apps/inventory': typeof AuthenticatedAppsInventoryRoute
  '/apps/kitting': typeof AuthenticatedAppsKittingRoute
  '/apps/my-productivity': typeof AuthenticatedAppsMyProductivityRoute
  '/apps/outbound': typeof AuthenticatedAppsOutboundRoute
  '/apps/production-boards': typeof AuthenticatedAppsProductionBoardsRoute
  '/apps/quality': typeof AuthenticatedAppsQualityRoute
  '/apps/shift-productivity': typeof AuthenticatedAppsShiftProductivityRoute
  '/apps/smartsheet-integrations': typeof AuthenticatedAppsSmartsheetIntegrationsRoute
  '/apps/standard-work': typeof AuthenticatedAppsStandardWorkRoute
  '/apps/tka-data-manager': typeof AuthenticatedAppsTkaDataManagerRoute
  '/apps/unit-pack': typeof AuthenticatedAppsUnitPackRoute
  '/business/customer-service': typeof AuthenticatedBusinessCustomerServiceRoute
  '/business/engineering': typeof AuthenticatedBusinessEngineeringRoute
  '/business/inventory': typeof AuthenticatedBusinessInventoryRoute
  '/business/logistics': typeof AuthenticatedBusinessLogisticsRoute
  '/business/supply-chain': typeof AuthenticatedBusinessSupplyChainRoute
  '/business/transportation': typeof AuthenticatedBusinessTransportationRoute
  '/business/warehouse': typeof AuthenticatedBusinessWarehouseRoute
  '/facility/it-services': typeof AuthenticatedFacilityItServicesRoute
  '/facility/maintenance': typeof AuthenticatedFacilityMaintenanceRoute
  '/facility/security': typeof AuthenticatedFacilitySecurityRoute
  '/facility/vendor-management': typeof AuthenticatedFacilityVendorManagementRoute
  '/hr/employee-reviews': typeof AuthenticatedHrEmployeeReviewsRoute
  '/hr/time-tracker': typeof AuthenticatedHrTimeTrackerRoute
  '/intelligence/ai-chat': typeof AuthenticatedIntelligenceAiChatRoute
  '/intelligence/drone-control': typeof AuthenticatedIntelligenceDroneControlRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/cache': typeof AuthenticatedSettingsCacheRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/admin/omnibelt': typeof AuthenticatedAdminOmnibeltIndexRoute
  '/admin/onboarding': typeof AuthenticatedAdminOnboardingIndexRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsIndexRoute
  '/admin/roles': typeof AuthenticatedAdminRolesIndexRoute
  '/admin/user-management': typeof AuthenticatedAdminUserManagementIndexRoute
  '/admin/work-engine': typeof AuthenticatedAdminWorkEngineIndexRoute
  '/admin/work-queue': typeof AuthenticatedAdminWorkQueueIndexRoute
}
export interface FileRoutesByTo {
  '/intro': typeof IntroRoute
  '/prototype': typeof PrototypeRoute
  '/scene3d-harness': typeof Scene3dHarnessRoute
  '/supply-chain-harness': typeof SupplyChainHarnessRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/rf-signin': typeof authRfSigninRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/customer-portal/$ticketId': typeof CustomerPortalTicketIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/customer-portal': typeof CustomerPortalIndexRoute
  '/rf-interface': typeof RfInterfaceIndexRoute
  '/timeclockapp': typeof TimeclockappIndexRoute
  '/admin/device-manager': typeof AuthenticatedAdminDeviceManagerRoute
  '/admin/performance-monitor': typeof AuthenticatedAdminPerformanceMonitorRoute
  '/admin/sap-testing': typeof AuthenticatedAdminSapTestingRoute
  '/admin/session-management': typeof AuthenticatedAdminSessionManagementRoute
  '/admin/supply-chain-mapping': typeof AuthenticatedAdminSupplyChainMappingRoute
  '/admin/system-settings': typeof AuthenticatedAdminSystemSettingsRoute
  '/admin/tab-permissions-debug': typeof AuthenticatedAdminTabPermissionsDebugRoute
  '/apps/customer-portal': typeof AuthenticatedAppsCustomerPortalRoute
  '/apps/data-manager': typeof AuthenticatedAppsDataManagerRoute
  '/apps/grs': typeof AuthenticatedAppsGrsRoute
  '/apps/inbound': typeof AuthenticatedAppsInboundRoute
  '/apps/inventory': typeof AuthenticatedAppsInventoryRoute
  '/apps/kitting': typeof AuthenticatedAppsKittingRoute
  '/apps/my-productivity': typeof AuthenticatedAppsMyProductivityRoute
  '/apps/outbound': typeof AuthenticatedAppsOutboundRoute
  '/apps/production-boards': typeof AuthenticatedAppsProductionBoardsRoute
  '/apps/quality': typeof AuthenticatedAppsQualityRoute
  '/apps/shift-productivity': typeof AuthenticatedAppsShiftProductivityRoute
  '/apps/smartsheet-integrations': typeof AuthenticatedAppsSmartsheetIntegrationsRoute
  '/apps/standard-work': typeof AuthenticatedAppsStandardWorkRoute
  '/apps/tka-data-manager': typeof AuthenticatedAppsTkaDataManagerRoute
  '/apps/unit-pack': typeof AuthenticatedAppsUnitPackRoute
  '/business/customer-service': typeof AuthenticatedBusinessCustomerServiceRoute
  '/business/engineering': typeof AuthenticatedBusinessEngineeringRoute
  '/business/inventory': typeof AuthenticatedBusinessInventoryRoute
  '/business/logistics': typeof AuthenticatedBusinessLogisticsRoute
  '/business/supply-chain': typeof AuthenticatedBusinessSupplyChainRoute
  '/business/transportation': typeof AuthenticatedBusinessTransportationRoute
  '/business/warehouse': typeof AuthenticatedBusinessWarehouseRoute
  '/facility/it-services': typeof AuthenticatedFacilityItServicesRoute
  '/facility/maintenance': typeof AuthenticatedFacilityMaintenanceRoute
  '/facility/security': typeof AuthenticatedFacilitySecurityRoute
  '/facility/vendor-management': typeof AuthenticatedFacilityVendorManagementRoute
  '/hr/employee-reviews': typeof AuthenticatedHrEmployeeReviewsRoute
  '/hr/time-tracker': typeof AuthenticatedHrTimeTrackerRoute
  '/intelligence/ai-chat': typeof AuthenticatedIntelligenceAiChatRoute
  '/intelligence/drone-control': typeof AuthenticatedIntelligenceDroneControlRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/cache': typeof AuthenticatedSettingsCacheRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/admin/omnibelt': typeof AuthenticatedAdminOmnibeltIndexRoute
  '/admin/onboarding': typeof AuthenticatedAdminOnboardingIndexRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsIndexRoute
  '/admin/roles': typeof AuthenticatedAdminRolesIndexRoute
  '/admin/user-management': typeof AuthenticatedAdminUserManagementIndexRoute
  '/admin/work-engine': typeof AuthenticatedAdminWorkEngineIndexRoute
  '/admin/work-queue': typeof AuthenticatedAdminWorkQueueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/intro': typeof IntroRoute
  '/prototype': typeof PrototypeRoute
  '/rf-interface': typeof RfInterfaceRouteWithChildren
  '/scene3d-harness': typeof Scene3dHarnessRoute
  '/supply-chain-harness': typeof SupplyChainHarnessRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/rf-signin': typeof authRfSigninRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/customer-portal/$ticketId': typeof CustomerPortalTicketIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/customer-portal/': typeof CustomerPortalIndexRoute
  '/rf-interface/': typeof RfInterfaceIndexRoute
  '/timeclockapp/': typeof TimeclockappIndexRoute
  '/_authenticated/admin/device-manager': typeof AuthenticatedAdminDeviceManagerRoute
  '/_authenticated/admin/performance-monitor': typeof AuthenticatedAdminPerformanceMonitorRoute
  '/_authenticated/admin/sap-testing': typeof AuthenticatedAdminSapTestingRoute
  '/_authenticated/admin/session-management': typeof AuthenticatedAdminSessionManagementRoute
  '/_authenticated/admin/supply-chain-mapping': typeof AuthenticatedAdminSupplyChainMappingRoute
  '/_authenticated/admin/system-settings': typeof AuthenticatedAdminSystemSettingsRoute
  '/_authenticated/admin/tab-permissions-debug': typeof AuthenticatedAdminTabPermissionsDebugRoute
  '/_authenticated/apps/customer-portal': typeof AuthenticatedAppsCustomerPortalRoute
  '/_authenticated/apps/data-manager': typeof AuthenticatedAppsDataManagerRoute
  '/_authenticated/apps/grs': typeof AuthenticatedAppsGrsRoute
  '/_authenticated/apps/inbound': typeof AuthenticatedAppsInboundRoute
  '/_authenticated/apps/inventory': typeof AuthenticatedAppsInventoryRoute
  '/_authenticated/apps/kitting': typeof AuthenticatedAppsKittingRoute
  '/_authenticated/apps/my-productivity': typeof AuthenticatedAppsMyProductivityRoute
  '/_authenticated/apps/outbound': typeof AuthenticatedAppsOutboundRoute
  '/_authenticated/apps/production-boards': typeof AuthenticatedAppsProductionBoardsRoute
  '/_authenticated/apps/quality': typeof AuthenticatedAppsQualityRoute
  '/_authenticated/apps/shift-productivity': typeof AuthenticatedAppsShiftProductivityRoute
  '/_authenticated/apps/smartsheet-integrations': typeof AuthenticatedAppsSmartsheetIntegrationsRoute
  '/_authenticated/apps/standard-work': typeof AuthenticatedAppsStandardWorkRoute
  '/_authenticated/apps/tka-data-manager': typeof AuthenticatedAppsTkaDataManagerRoute
  '/_authenticated/apps/unit-pack': typeof AuthenticatedAppsUnitPackRoute
  '/_authenticated/business/customer-service': typeof AuthenticatedBusinessCustomerServiceRoute
  '/_authenticated/business/engineering': typeof AuthenticatedBusinessEngineeringRoute
  '/_authenticated/business/inventory': typeof AuthenticatedBusinessInventoryRoute
  '/_authenticated/business/logistics': typeof AuthenticatedBusinessLogisticsRoute
  '/_authenticated/business/supply-chain': typeof AuthenticatedBusinessSupplyChainRoute
  '/_authenticated/business/transportation': typeof AuthenticatedBusinessTransportationRoute
  '/_authenticated/business/warehouse': typeof AuthenticatedBusinessWarehouseRoute
  '/_authenticated/facility/it-services': typeof AuthenticatedFacilityItServicesRoute
  '/_authenticated/facility/maintenance': typeof AuthenticatedFacilityMaintenanceRoute
  '/_authenticated/facility/security': typeof AuthenticatedFacilitySecurityRoute
  '/_authenticated/facility/vendor-management': typeof AuthenticatedFacilityVendorManagementRoute
  '/_authenticated/hr/employee-reviews': typeof AuthenticatedHrEmployeeReviewsRoute
  '/_authenticated/hr/time-tracker': typeof AuthenticatedHrTimeTrackerRoute
  '/_authenticated/intelligence/ai-chat': typeof AuthenticatedIntelligenceAiChatRoute
  '/_authenticated/intelligence/drone-control': typeof AuthenticatedIntelligenceDroneControlRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/cache': typeof AuthenticatedSettingsCacheRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/admin/omnibelt/': typeof AuthenticatedAdminOmnibeltIndexRoute
  '/_authenticated/admin/onboarding/': typeof AuthenticatedAdminOnboardingIndexRoute
  '/_authenticated/admin/permissions/': typeof AuthenticatedAdminPermissionsIndexRoute
  '/_authenticated/admin/roles/': typeof AuthenticatedAdminRolesIndexRoute
  '/_authenticated/admin/user-management/': typeof AuthenticatedAdminUserManagementIndexRoute
  '/_authenticated/admin/work-engine/': typeof AuthenticatedAdminWorkEngineIndexRoute
  '/_authenticated/admin/work-queue/': typeof AuthenticatedAdminWorkQueueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/intro'
    | '/prototype'
    | '/rf-interface'
    | '/scene3d-harness'
    | '/supply-chain-harness'
    | '/admin'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/rf-signin'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/customer-portal/$ticketId'
    | '/'
    | '/customer-portal'
    | '/rf-interface/'
    | '/timeclockapp'
    | '/admin/device-manager'
    | '/admin/performance-monitor'
    | '/admin/sap-testing'
    | '/admin/session-management'
    | '/admin/supply-chain-mapping'
    | '/admin/system-settings'
    | '/admin/tab-permissions-debug'
    | '/apps/customer-portal'
    | '/apps/data-manager'
    | '/apps/grs'
    | '/apps/inbound'
    | '/apps/inventory'
    | '/apps/kitting'
    | '/apps/my-productivity'
    | '/apps/outbound'
    | '/apps/production-boards'
    | '/apps/quality'
    | '/apps/shift-productivity'
    | '/apps/smartsheet-integrations'
    | '/apps/standard-work'
    | '/apps/tka-data-manager'
    | '/apps/unit-pack'
    | '/business/customer-service'
    | '/business/engineering'
    | '/business/inventory'
    | '/business/logistics'
    | '/business/supply-chain'
    | '/business/transportation'
    | '/business/warehouse'
    | '/facility/it-services'
    | '/facility/maintenance'
    | '/facility/security'
    | '/facility/vendor-management'
    | '/hr/employee-reviews'
    | '/hr/time-tracker'
    | '/intelligence/ai-chat'
    | '/intelligence/drone-control'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/cache'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/organization'
    | '/help-center'
    | '/settings/'
    | '/tasks'
    | '/admin/omnibelt'
    | '/admin/onboarding'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/user-management'
    | '/admin/work-engine'
    | '/admin/work-queue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/intro'
    | '/prototype'
    | '/scene3d-harness'
    | '/supply-chain-harness'
    | '/admin'
    | '/forgot-password'
    | '/otp'
    | '/rf-signin'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/customer-portal/$ticketId'
    | '/'
    | '/customer-portal'
    | '/rf-interface'
    | '/timeclockapp'
    | '/admin/device-manager'
    | '/admin/performance-monitor'
    | '/admin/sap-testing'
    | '/admin/session-management'
    | '/admin/supply-chain-mapping'
    | '/admin/system-settings'
    | '/admin/tab-permissions-debug'
    | '/apps/customer-portal'
    | '/apps/data-manager'
    | '/apps/grs'
    | '/apps/inbound'
    | '/apps/inventory'
    | '/apps/kitting'
    | '/apps/my-productivity'
    | '/apps/outbound'
    | '/apps/production-boards'
    | '/apps/quality'
    | '/apps/shift-productivity'
    | '/apps/smartsheet-integrations'
    | '/apps/standard-work'
    | '/apps/tka-data-manager'
    | '/apps/unit-pack'
    | '/business/customer-service'
    | '/business/engineering'
    | '/business/inventory'
    | '/business/logistics'
    | '/business/supply-chain'
    | '/business/transportation'
    | '/business/warehouse'
    | '/facility/it-services'
    | '/facility/maintenance'
    | '/facility/security'
    | '/facility/vendor-management'
    | '/hr/employee-reviews'
    | '/hr/time-tracker'
    | '/intelligence/ai-chat'
    | '/intelligence/drone-control'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/cache'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/organization'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/admin/omnibelt'
    | '/admin/onboarding'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/user-management'
    | '/admin/work-engine'
    | '/admin/work-queue'
  id:
    | '__root__'
    | '/_authenticated'
    | '/intro'
    | '/prototype'
    | '/rf-interface'
    | '/scene3d-harness'
    | '/supply-chain-harness'
    | '/_authenticated/admin'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/rf-signin'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/customer-portal/$ticketId'
    | '/_authenticated/'
    | '/customer-portal/'
    | '/rf-interface/'
    | '/timeclockapp/'
    | '/_authenticated/admin/device-manager'
    | '/_authenticated/admin/performance-monitor'
    | '/_authenticated/admin/sap-testing'
    | '/_authenticated/admin/session-management'
    | '/_authenticated/admin/supply-chain-mapping'
    | '/_authenticated/admin/system-settings'
    | '/_authenticated/admin/tab-permissions-debug'
    | '/_authenticated/apps/customer-portal'
    | '/_authenticated/apps/data-manager'
    | '/_authenticated/apps/grs'
    | '/_authenticated/apps/inbound'
    | '/_authenticated/apps/inventory'
    | '/_authenticated/apps/kitting'
    | '/_authenticated/apps/my-productivity'
    | '/_authenticated/apps/outbound'
    | '/_authenticated/apps/production-boards'
    | '/_authenticated/apps/quality'
    | '/_authenticated/apps/shift-productivity'
    | '/_authenticated/apps/smartsheet-integrations'
    | '/_authenticated/apps/standard-work'
    | '/_authenticated/apps/tka-data-manager'
    | '/_authenticated/apps/unit-pack'
    | '/_authenticated/business/customer-service'
    | '/_authenticated/business/engineering'
    | '/_authenticated/business/inventory'
    | '/_authenticated/business/logistics'
    | '/_authenticated/business/supply-chain'
    | '/_authenticated/business/transportation'
    | '/_authenticated/business/warehouse'
    | '/_authenticated/facility/it-services'
    | '/_authenticated/facility/maintenance'
    | '/_authenticated/facility/security'
    | '/_authenticated/facility/vendor-management'
    | '/_authenticated/hr/employee-reviews'
    | '/_authenticated/hr/time-tracker'
    | '/_authenticated/intelligence/ai-chat'
    | '/_authenticated/intelligence/drone-control'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/cache'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/organization'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/admin/omnibelt/'
    | '/_authenticated/admin/onboarding/'
    | '/_authenticated/admin/permissions/'
    | '/_authenticated/admin/roles/'
    | '/_authenticated/admin/user-management/'
    | '/_authenticated/admin/work-engine/'
    | '/_authenticated/admin/work-queue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  IntroRoute: typeof IntroRoute
  PrototypeRoute: typeof PrototypeRoute
  RfInterfaceRoute: typeof RfInterfaceRouteWithChildren
  Scene3dHarnessRoute: typeof Scene3dHarnessRoute
  SupplyChainHarnessRoute: typeof SupplyChainHarnessRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authRfSigninRoute: typeof authRfSigninRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  CustomerPortalTicketIdRoute: typeof CustomerPortalTicketIdRoute
  CustomerPortalIndexRoute: typeof CustomerPortalIndexRoute
  TimeclockappIndexRoute: typeof TimeclockappIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supply-chain-harness': {
      id: '/supply-chain-harness'
      path: '/supply-chain-harness'
      fullPath: '/supply-chain-harness'
      preLoaderRoute: typeof SupplyChainHarnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene3d-harness': {
      id: '/scene3d-harness'
      path: '/scene3d-harness'
      fullPath: '/scene3d-harness'
      preLoaderRoute: typeof Scene3dHarnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rf-interface': {
      id: '/rf-interface'
      path: '/rf-interface'
      fullPath: '/rf-interface'
      preLoaderRoute: typeof RfInterfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype': {
      id: '/prototype'
      path: '/prototype'
      fullPath: '/prototype'
      preLoaderRoute: typeof PrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeclockapp/': {
      id: '/timeclockapp/'
      path: '/timeclockapp'
      fullPath: '/timeclockapp'
      preLoaderRoute: typeof TimeclockappIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rf-interface/': {
      id: '/rf-interface/'
      path: '/'
      fullPath: '/rf-interface/'
      preLoaderRoute: typeof RfInterfaceIndexRouteImport
      parentRoute: typeof RfInterfaceRoute
    }
    '/customer-portal/': {
      id: '/customer-portal/'
      path: '/customer-portal'
      fullPath: '/customer-portal'
      preLoaderRoute: typeof CustomerPortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/customer-portal/$ticketId': {
      id: '/customer-portal/$ticketId'
      path: '/customer-portal/$ticketId'
      fullPath: '/customer-portal/$ticketId'
      preLoaderRoute: typeof CustomerPortalTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/rf-signin': {
      id: '/(auth)/rf-signin'
      path: '/rf-signin'
      fullPath: '/rf-signin'
      preLoaderRoute: typeof authRfSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/organization': {
      id: '/_authenticated/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/cache': {
      id: '/_authenticated/settings/cache'
      path: '/cache'
      fullPath: '/settings/cache'
      preLoaderRoute: typeof AuthenticatedSettingsCacheRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/intelligence/drone-control': {
      id: '/_authenticated/intelligence/drone-control'
      path: '/intelligence/drone-control'
      fullPath: '/intelligence/drone-control'
      preLoaderRoute: typeof AuthenticatedIntelligenceDroneControlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intelligence/ai-chat': {
      id: '/_authenticated/intelligence/ai-chat'
      path: '/intelligence/ai-chat'
      fullPath: '/intelligence/ai-chat'
      preLoaderRoute: typeof AuthenticatedIntelligenceAiChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/time-tracker': {
      id: '/_authenticated/hr/time-tracker'
      path: '/hr/time-tracker'
      fullPath: '/hr/time-tracker'
      preLoaderRoute: typeof AuthenticatedHrTimeTrackerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/employee-reviews': {
      id: '/_authenticated/hr/employee-reviews'
      path: '/hr/employee-reviews'
      fullPath: '/hr/employee-reviews'
      preLoaderRoute: typeof AuthenticatedHrEmployeeReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facility/vendor-management': {
      id: '/_authenticated/facility/vendor-management'
      path: '/facility/vendor-management'
      fullPath: '/facility/vendor-management'
      preLoaderRoute: typeof AuthenticatedFacilityVendorManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facility/security': {
      id: '/_authenticated/facility/security'
      path: '/facility/security'
      fullPath: '/facility/security'
      preLoaderRoute: typeof AuthenticatedFacilitySecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facility/maintenance': {
      id: '/_authenticated/facility/maintenance'
      path: '/facility/maintenance'
      fullPath: '/facility/maintenance'
      preLoaderRoute: typeof AuthenticatedFacilityMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facility/it-services': {
      id: '/_authenticated/facility/it-services'
      path: '/facility/it-services'
      fullPath: '/facility/it-services'
      preLoaderRoute: typeof AuthenticatedFacilityItServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/warehouse': {
      id: '/_authenticated/business/warehouse'
      path: '/business/warehouse'
      fullPath: '/business/warehouse'
      preLoaderRoute: typeof AuthenticatedBusinessWarehouseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/transportation': {
      id: '/_authenticated/business/transportation'
      path: '/business/transportation'
      fullPath: '/business/transportation'
      preLoaderRoute: typeof AuthenticatedBusinessTransportationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/supply-chain': {
      id: '/_authenticated/business/supply-chain'
      path: '/business/supply-chain'
      fullPath: '/business/supply-chain'
      preLoaderRoute: typeof AuthenticatedBusinessSupplyChainRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/logistics': {
      id: '/_authenticated/business/logistics'
      path: '/business/logistics'
      fullPath: '/business/logistics'
      preLoaderRoute: typeof AuthenticatedBusinessLogisticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/inventory': {
      id: '/_authenticated/business/inventory'
      path: '/business/inventory'
      fullPath: '/business/inventory'
      preLoaderRoute: typeof AuthenticatedBusinessInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/engineering': {
      id: '/_authenticated/business/engineering'
      path: '/business/engineering'
      fullPath: '/business/engineering'
      preLoaderRoute: typeof AuthenticatedBusinessEngineeringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/customer-service': {
      id: '/_authenticated/business/customer-service'
      path: '/business/customer-service'
      fullPath: '/business/customer-service'
      preLoaderRoute: typeof AuthenticatedBusinessCustomerServiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/unit-pack': {
      id: '/_authenticated/apps/unit-pack'
      path: '/apps/unit-pack'
      fullPath: '/apps/unit-pack'
      preLoaderRoute: typeof AuthenticatedAppsUnitPackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/tka-data-manager': {
      id: '/_authenticated/apps/tka-data-manager'
      path: '/apps/tka-data-manager'
      fullPath: '/apps/tka-data-manager'
      preLoaderRoute: typeof AuthenticatedAppsTkaDataManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/standard-work': {
      id: '/_authenticated/apps/standard-work'
      path: '/apps/standard-work'
      fullPath: '/apps/standard-work'
      preLoaderRoute: typeof AuthenticatedAppsStandardWorkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/smartsheet-integrations': {
      id: '/_authenticated/apps/smartsheet-integrations'
      path: '/apps/smartsheet-integrations'
      fullPath: '/apps/smartsheet-integrations'
      preLoaderRoute: typeof AuthenticatedAppsSmartsheetIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/shift-productivity': {
      id: '/_authenticated/apps/shift-productivity'
      path: '/apps/shift-productivity'
      fullPath: '/apps/shift-productivity'
      preLoaderRoute: typeof AuthenticatedAppsShiftProductivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/quality': {
      id: '/_authenticated/apps/quality'
      path: '/apps/quality'
      fullPath: '/apps/quality'
      preLoaderRoute: typeof AuthenticatedAppsQualityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/production-boards': {
      id: '/_authenticated/apps/production-boards'
      path: '/apps/production-boards'
      fullPath: '/apps/production-boards'
      preLoaderRoute: typeof AuthenticatedAppsProductionBoardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/outbound': {
      id: '/_authenticated/apps/outbound'
      path: '/apps/outbound'
      fullPath: '/apps/outbound'
      preLoaderRoute: typeof AuthenticatedAppsOutboundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/my-productivity': {
      id: '/_authenticated/apps/my-productivity'
      path: '/apps/my-productivity'
      fullPath: '/apps/my-productivity'
      preLoaderRoute: typeof AuthenticatedAppsMyProductivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/kitting': {
      id: '/_authenticated/apps/kitting'
      path: '/apps/kitting'
      fullPath: '/apps/kitting'
      preLoaderRoute: typeof AuthenticatedAppsKittingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/inventory': {
      id: '/_authenticated/apps/inventory'
      path: '/apps/inventory'
      fullPath: '/apps/inventory'
      preLoaderRoute: typeof AuthenticatedAppsInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/inbound': {
      id: '/_authenticated/apps/inbound'
      path: '/apps/inbound'
      fullPath: '/apps/inbound'
      preLoaderRoute: typeof AuthenticatedAppsInboundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/grs': {
      id: '/_authenticated/apps/grs'
      path: '/apps/grs'
      fullPath: '/apps/grs'
      preLoaderRoute: typeof AuthenticatedAppsGrsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/data-manager': {
      id: '/_authenticated/apps/data-manager'
      path: '/apps/data-manager'
      fullPath: '/apps/data-manager'
      preLoaderRoute: typeof AuthenticatedAppsDataManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/customer-portal': {
      id: '/_authenticated/apps/customer-portal'
      path: '/apps/customer-portal'
      fullPath: '/apps/customer-portal'
      preLoaderRoute: typeof AuthenticatedAppsCustomerPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tab-permissions-debug': {
      id: '/_authenticated/admin/tab-permissions-debug'
      path: '/tab-permissions-debug'
      fullPath: '/admin/tab-permissions-debug'
      preLoaderRoute: typeof AuthenticatedAdminTabPermissionsDebugRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/system-settings': {
      id: '/_authenticated/admin/system-settings'
      path: '/system-settings'
      fullPath: '/admin/system-settings'
      preLoaderRoute: typeof AuthenticatedAdminSystemSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/supply-chain-mapping': {
      id: '/_authenticated/admin/supply-chain-mapping'
      path: '/supply-chain-mapping'
      fullPath: '/admin/supply-chain-mapping'
      preLoaderRoute: typeof AuthenticatedAdminSupplyChainMappingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/session-management': {
      id: '/_authenticated/admin/session-management'
      path: '/session-management'
      fullPath: '/admin/session-management'
      preLoaderRoute: typeof AuthenticatedAdminSessionManagementRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sap-testing': {
      id: '/_authenticated/admin/sap-testing'
      path: '/sap-testing'
      fullPath: '/admin/sap-testing'
      preLoaderRoute: typeof AuthenticatedAdminSapTestingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/performance-monitor': {
      id: '/_authenticated/admin/performance-monitor'
      path: '/performance-monitor'
      fullPath: '/admin/performance-monitor'
      preLoaderRoute: typeof AuthenticatedAdminPerformanceMonitorRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/device-manager': {
      id: '/_authenticated/admin/device-manager'
      path: '/device-manager'
      fullPath: '/admin/device-manager'
      preLoaderRoute: typeof AuthenticatedAdminDeviceManagerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/work-queue/': {
      id: '/_authenticated/admin/work-queue/'
      path: '/work-queue'
      fullPath: '/admin/work-queue'
      preLoaderRoute: typeof AuthenticatedAdminWorkQueueIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/work-engine/': {
      id: '/_authenticated/admin/work-engine/'
      path: '/work-engine'
      fullPath: '/admin/work-engine'
      preLoaderRoute: typeof AuthenticatedAdminWorkEngineIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/user-management/': {
      id: '/_authenticated/admin/user-management/'
      path: '/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof AuthenticatedAdminUserManagementIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/roles/': {
      id: '/_authenticated/admin/roles/'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/permissions/': {
      id: '/_authenticated/admin/permissions/'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/onboarding/': {
      id: '/_authenticated/admin/onboarding/'
      path: '/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AuthenticatedAdminOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/omnibelt/': {
      id: '/_authenticated/admin/omnibelt/'
      path: '/omnibelt'
      fullPath: '/admin/omnibelt'
      preLoaderRoute: typeof AuthenticatedAdminOmnibeltIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminDeviceManagerRoute: typeof AuthenticatedAdminDeviceManagerRoute
  AuthenticatedAdminPerformanceMonitorRoute: typeof AuthenticatedAdminPerformanceMonitorRoute
  AuthenticatedAdminSapTestingRoute: typeof AuthenticatedAdminSapTestingRoute
  AuthenticatedAdminSessionManagementRoute: typeof AuthenticatedAdminSessionManagementRoute
  AuthenticatedAdminSupplyChainMappingRoute: typeof AuthenticatedAdminSupplyChainMappingRoute
  AuthenticatedAdminSystemSettingsRoute: typeof AuthenticatedAdminSystemSettingsRoute
  AuthenticatedAdminTabPermissionsDebugRoute: typeof AuthenticatedAdminTabPermissionsDebugRoute
  AuthenticatedAdminOmnibeltIndexRoute: typeof AuthenticatedAdminOmnibeltIndexRoute
  AuthenticatedAdminOnboardingIndexRoute: typeof AuthenticatedAdminOnboardingIndexRoute
  AuthenticatedAdminPermissionsIndexRoute: typeof AuthenticatedAdminPermissionsIndexRoute
  AuthenticatedAdminRolesIndexRoute: typeof AuthenticatedAdminRolesIndexRoute
  AuthenticatedAdminUserManagementIndexRoute: typeof AuthenticatedAdminUserManagementIndexRoute
  AuthenticatedAdminWorkEngineIndexRoute: typeof AuthenticatedAdminWorkEngineIndexRoute
  AuthenticatedAdminWorkQueueIndexRoute: typeof AuthenticatedAdminWorkQueueIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminDeviceManagerRoute: AuthenticatedAdminDeviceManagerRoute,
    AuthenticatedAdminPerformanceMonitorRoute:
      AuthenticatedAdminPerformanceMonitorRoute,
    AuthenticatedAdminSapTestingRoute: AuthenticatedAdminSapTestingRoute,
    AuthenticatedAdminSessionManagementRoute:
      AuthenticatedAdminSessionManagementRoute,
    AuthenticatedAdminSupplyChainMappingRoute:
      AuthenticatedAdminSupplyChainMappingRoute,
    AuthenticatedAdminSystemSettingsRoute:
      AuthenticatedAdminSystemSettingsRoute,
    AuthenticatedAdminTabPermissionsDebugRoute:
      AuthenticatedAdminTabPermissionsDebugRoute,
    AuthenticatedAdminOmnibeltIndexRoute: AuthenticatedAdminOmnibeltIndexRoute,
    AuthenticatedAdminOnboardingIndexRoute:
      AuthenticatedAdminOnboardingIndexRoute,
    AuthenticatedAdminPermissionsIndexRoute:
      AuthenticatedAdminPermissionsIndexRoute,
    AuthenticatedAdminRolesIndexRoute: AuthenticatedAdminRolesIndexRoute,
    AuthenticatedAdminUserManagementIndexRoute:
      AuthenticatedAdminUserManagementIndexRoute,
    AuthenticatedAdminWorkEngineIndexRoute:
      AuthenticatedAdminWorkEngineIndexRoute,
    AuthenticatedAdminWorkQueueIndexRoute:
      AuthenticatedAdminWorkQueueIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsCacheRoute: typeof AuthenticatedSettingsCacheRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsOrganizationRoute: typeof AuthenticatedSettingsOrganizationRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsCacheRoute: AuthenticatedSettingsCacheRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsOrganizationRoute:
      AuthenticatedSettingsOrganizationRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAppsCustomerPortalRoute: typeof AuthenticatedAppsCustomerPortalRoute
  AuthenticatedAppsDataManagerRoute: typeof AuthenticatedAppsDataManagerRoute
  AuthenticatedAppsGrsRoute: typeof AuthenticatedAppsGrsRoute
  AuthenticatedAppsInboundRoute: typeof AuthenticatedAppsInboundRoute
  AuthenticatedAppsInventoryRoute: typeof AuthenticatedAppsInventoryRoute
  AuthenticatedAppsKittingRoute: typeof AuthenticatedAppsKittingRoute
  AuthenticatedAppsMyProductivityRoute: typeof AuthenticatedAppsMyProductivityRoute
  AuthenticatedAppsOutboundRoute: typeof AuthenticatedAppsOutboundRoute
  AuthenticatedAppsProductionBoardsRoute: typeof AuthenticatedAppsProductionBoardsRoute
  AuthenticatedAppsQualityRoute: typeof AuthenticatedAppsQualityRoute
  AuthenticatedAppsShiftProductivityRoute: typeof AuthenticatedAppsShiftProductivityRoute
  AuthenticatedAppsSmartsheetIntegrationsRoute: typeof AuthenticatedAppsSmartsheetIntegrationsRoute
  AuthenticatedAppsStandardWorkRoute: typeof AuthenticatedAppsStandardWorkRoute
  AuthenticatedAppsTkaDataManagerRoute: typeof AuthenticatedAppsTkaDataManagerRoute
  AuthenticatedAppsUnitPackRoute: typeof AuthenticatedAppsUnitPackRoute
  AuthenticatedBusinessCustomerServiceRoute: typeof AuthenticatedBusinessCustomerServiceRoute
  AuthenticatedBusinessEngineeringRoute: typeof AuthenticatedBusinessEngineeringRoute
  AuthenticatedBusinessInventoryRoute: typeof AuthenticatedBusinessInventoryRoute
  AuthenticatedBusinessLogisticsRoute: typeof AuthenticatedBusinessLogisticsRoute
  AuthenticatedBusinessSupplyChainRoute: typeof AuthenticatedBusinessSupplyChainRoute
  AuthenticatedBusinessTransportationRoute: typeof AuthenticatedBusinessTransportationRoute
  AuthenticatedBusinessWarehouseRoute: typeof AuthenticatedBusinessWarehouseRoute
  AuthenticatedFacilityItServicesRoute: typeof AuthenticatedFacilityItServicesRoute
  AuthenticatedFacilityMaintenanceRoute: typeof AuthenticatedFacilityMaintenanceRoute
  AuthenticatedFacilitySecurityRoute: typeof AuthenticatedFacilitySecurityRoute
  AuthenticatedFacilityVendorManagementRoute: typeof AuthenticatedFacilityVendorManagementRoute
  AuthenticatedHrEmployeeReviewsRoute: typeof AuthenticatedHrEmployeeReviewsRoute
  AuthenticatedHrTimeTrackerRoute: typeof AuthenticatedHrTimeTrackerRoute
  AuthenticatedIntelligenceAiChatRoute: typeof AuthenticatedIntelligenceAiChatRoute
  AuthenticatedIntelligenceDroneControlRoute: typeof AuthenticatedIntelligenceDroneControlRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAppsCustomerPortalRoute: AuthenticatedAppsCustomerPortalRoute,
  AuthenticatedAppsDataManagerRoute: AuthenticatedAppsDataManagerRoute,
  AuthenticatedAppsGrsRoute: AuthenticatedAppsGrsRoute,
  AuthenticatedAppsInboundRoute: AuthenticatedAppsInboundRoute,
  AuthenticatedAppsInventoryRoute: AuthenticatedAppsInventoryRoute,
  AuthenticatedAppsKittingRoute: AuthenticatedAppsKittingRoute,
  AuthenticatedAppsMyProductivityRoute: AuthenticatedAppsMyProductivityRoute,
  AuthenticatedAppsOutboundRoute: AuthenticatedAppsOutboundRoute,
  AuthenticatedAppsProductionBoardsRoute:
    AuthenticatedAppsProductionBoardsRoute,
  AuthenticatedAppsQualityRoute: AuthenticatedAppsQualityRoute,
  AuthenticatedAppsShiftProductivityRoute:
    AuthenticatedAppsShiftProductivityRoute,
  AuthenticatedAppsSmartsheetIntegrationsRoute:
    AuthenticatedAppsSmartsheetIntegrationsRoute,
  AuthenticatedAppsStandardWorkRoute: AuthenticatedAppsStandardWorkRoute,
  AuthenticatedAppsTkaDataManagerRoute: AuthenticatedAppsTkaDataManagerRoute,
  AuthenticatedAppsUnitPackRoute: AuthenticatedAppsUnitPackRoute,
  AuthenticatedBusinessCustomerServiceRoute:
    AuthenticatedBusinessCustomerServiceRoute,
  AuthenticatedBusinessEngineeringRoute: AuthenticatedBusinessEngineeringRoute,
  AuthenticatedBusinessInventoryRoute: AuthenticatedBusinessInventoryRoute,
  AuthenticatedBusinessLogisticsRoute: AuthenticatedBusinessLogisticsRoute,
  AuthenticatedBusinessSupplyChainRoute: AuthenticatedBusinessSupplyChainRoute,
  AuthenticatedBusinessTransportationRoute:
    AuthenticatedBusinessTransportationRoute,
  AuthenticatedBusinessWarehouseRoute: AuthenticatedBusinessWarehouseRoute,
  AuthenticatedFacilityItServicesRoute: AuthenticatedFacilityItServicesRoute,
  AuthenticatedFacilityMaintenanceRoute: AuthenticatedFacilityMaintenanceRoute,
  AuthenticatedFacilitySecurityRoute: AuthenticatedFacilitySecurityRoute,
  AuthenticatedFacilityVendorManagementRoute:
    AuthenticatedFacilityVendorManagementRoute,
  AuthenticatedHrEmployeeReviewsRoute: AuthenticatedHrEmployeeReviewsRoute,
  AuthenticatedHrTimeTrackerRoute: AuthenticatedHrTimeTrackerRoute,
  AuthenticatedIntelligenceAiChatRoute: AuthenticatedIntelligenceAiChatRoute,
  AuthenticatedIntelligenceDroneControlRoute:
    AuthenticatedIntelligenceDroneControlRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface RfInterfaceRouteChildren {
  RfInterfaceIndexRoute: typeof RfInterfaceIndexRoute
}

const RfInterfaceRouteChildren: RfInterfaceRouteChildren = {
  RfInterfaceIndexRoute: RfInterfaceIndexRoute,
}

const RfInterfaceRouteWithChildren = RfInterfaceRoute._addFileChildren(
  RfInterfaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  IntroRoute: IntroRoute,
  PrototypeRoute: PrototypeRoute,
  RfInterfaceRoute: RfInterfaceRouteWithChildren,
  Scene3dHarnessRoute: Scene3dHarnessRoute,
  SupplyChainHarnessRoute: SupplyChainHarnessRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authRfSigninRoute: authRfSigninRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  CustomerPortalTicketIdRoute: CustomerPortalTicketIdRoute,
  CustomerPortalIndexRoute: CustomerPortalIndexRoute,
  TimeclockappIndexRoute: TimeclockappIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
